services:
  app:
    build: .
    container_name: time-logger-app
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://freelance_user:freelance_pass@db:27017/freelance_db?authSource=admin

  db:
    image: mongo:6
    container_name: freelance_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: freelance_user
      MONGO_INITDB_ROOT_PASSWORD: freelance_pass
      MONGO_INITDB_DATABASE: freelance_db
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
